### ISSUE TITLE
fusesma.sim/fuserouting.sim/fuse

### ISSUE THREAD

**Issue by maelle** [cvitolo/fuse#11]
This issue is part of [this JOSS review](https://github.com/openjournals/joss-reviews/issues/52)

Why not have the random seed as argument of `fusesma.sim` and `fuserouting.sim` and `fuse` (or of `fuse`only since it calls both other functions), with a default value, to make results reproducible even if the user forgets about the seed?

**Comment by cvitolo** [comment]
The functions fusesma.sim, fuserouting.sim and fuse do not generate internally the parameter sets but uses pre-defined ones because there are various ways of sampling the parameter ranges. The function generateParameters() only uses one of them (latin hypercube). For this reason, the parameter sets should be generated prior to using fuse and not within it.

**Comment by maelle** [comment]
But you still use a random seed before calling them, right? Not important though :-)

**Comment by cvitolo** [comment]
Sorry, I should have clarified that I only set the seed before running `generateParameters` to have always the same parameters in my examples.
