### ISSUE TITLE
Name and format of DATA

### ISSUE THREAD

**Issue by maelle** [cvitolo/fuse#4]
This issue is part of [this JOSS review](https://github.com/openjournals/joss-reviews/issues/52)

The most important remark of this issue: the doc states DATA is a data.frame but it's actually a `zoo` object, could you update the doc or the object itself?

These are details and only suggestions:

* The name "DATA" is not very specific, why not name the sample data fuse_hydrological_data or something like that? If it's a time series, maybe even fuse_hydrological_timeseries?

* The names of the columns/variables could be replaced by the full name of the variables, e.g. "precipitation" instead of P.

**Comment by maelle** [comment]
By the way since it is a `zoo` object, in the doc you could add "plot(DATA)" in Examples, it's quite nice one gets to see the time series so easily. :-)

**Comment by cvitolo** [comment]
I have changed the name DATA to fuse_hydrological_timeseries and updated the documentation (format is now zoo) and added plot(fuse_hydrological_timeseries) to the examples in the doc.

I cannot changed the name of the name of the columns because this is a convention in modelling frameworks (e.g. Fortran fuse and hydromad).

**Comment by maelle** [comment]
Ok, cool!
